// <auto-generated />
using System;
using ECommerce.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Data.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20250421164411_AddCartTables")]
    partial class AddCartTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Core.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 1. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 1",
                            Price = 16.49m,
                            Stock = 102
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 2. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 2",
                            Price = 21.99m,
                            Stock = 104
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 3. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 3",
                            Price = 27.49m,
                            Stock = 106
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 4. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 4",
                            Price = 32.99m,
                            Stock = 108
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 5. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 5",
                            Price = 38.49m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 6. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 6",
                            Price = 43.99m,
                            Stock = 112
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 7. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 7",
                            Price = 49.49m,
                            Stock = 114
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 8. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 8",
                            Price = 54.99m,
                            Stock = 116
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 9. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 9",
                            Price = 60.49m,
                            Stock = 118
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 10. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 10",
                            Price = 65.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 11. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 11",
                            Price = 71.49m,
                            Stock = 122
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 12. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 12",
                            Price = 76.99m,
                            Stock = 124
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 13. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 13",
                            Price = 82.49m,
                            Stock = 126
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 14. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 14",
                            Price = 87.99m,
                            Stock = 128
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 15. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 15",
                            Price = 93.49m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 16. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 16",
                            Price = 98.99m,
                            Stock = 132
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 17. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 17",
                            Price = 104.49m,
                            Stock = 134
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 18. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 18",
                            Price = 109.99m,
                            Stock = 136
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 19. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 19",
                            Price = 115.49m,
                            Stock = 138
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 20. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 20",
                            Price = 120.99m,
                            Stock = 140
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 21. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 21",
                            Price = 126.49m,
                            Stock = 142
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 22. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 22",
                            Price = 131.99m,
                            Stock = 144
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 23. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 23",
                            Price = 137.49m,
                            Stock = 146
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 24. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 24",
                            Price = 142.99m,
                            Stock = 148
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 25. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 25",
                            Price = 148.49m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 26. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 26",
                            Price = 153.99m,
                            Stock = 152
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 27. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 27",
                            Price = 159.49m,
                            Stock = 154
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 28. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 28",
                            Price = 164.99m,
                            Stock = 156
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 29. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 29",
                            Price = 170.49m,
                            Stock = 158
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 30. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 30",
                            Price = 175.99m,
                            Stock = 160
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 31. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 31",
                            Price = 181.49m,
                            Stock = 162
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 32. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 32",
                            Price = 186.99m,
                            Stock = 164
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 33. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 33",
                            Price = 192.49m,
                            Stock = 166
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 34. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 34",
                            Price = 197.99m,
                            Stock = 168
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 35. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 35",
                            Price = 203.49m,
                            Stock = 170
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 36. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 36",
                            Price = 208.99m,
                            Stock = 172
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 37. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 37",
                            Price = 214.49m,
                            Stock = 174
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 38. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 38",
                            Price = 219.99m,
                            Stock = 176
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 39. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 39",
                            Price = 225.49m,
                            Stock = 178
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 40. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 40",
                            Price = 230.99m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 41. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 41",
                            Price = 236.49m,
                            Stock = 182
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 42. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 42",
                            Price = 241.99m,
                            Stock = 184
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 43. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 43",
                            Price = 247.49m,
                            Stock = 186
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 44. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 44",
                            Price = 252.99m,
                            Stock = 188
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 45. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 45",
                            Price = 258.49m,
                            Stock = 190
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 46. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 46",
                            Price = 263.99m,
                            Stock = 192
                        },
                        new
                        {
                            Id = 47,
                            CreatedDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 47. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 47",
                            Price = 269.49m,
                            Stock = 194
                        },
                        new
                        {
                            Id = 48,
                            CreatedDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 48. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 48",
                            Price = 274.99m,
                            Stock = 196
                        },
                        new
                        {
                            Id = 49,
                            CreatedDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 49. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 49",
                            Price = 280.49m,
                            Stock = 198
                        },
                        new
                        {
                            Id = 50,
                            CreatedDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 50. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 50",
                            Price = 285.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 51,
                            CreatedDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 51. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 51",
                            Price = 291.49m,
                            Stock = 202
                        },
                        new
                        {
                            Id = 52,
                            CreatedDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 52. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 52",
                            Price = 296.99m,
                            Stock = 204
                        },
                        new
                        {
                            Id = 53,
                            CreatedDate = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 53. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 53",
                            Price = 302.49m,
                            Stock = 206
                        },
                        new
                        {
                            Id = 54,
                            CreatedDate = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 54. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 54",
                            Price = 307.99m,
                            Stock = 208
                        },
                        new
                        {
                            Id = 55,
                            CreatedDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 55. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 55",
                            Price = 313.49m,
                            Stock = 210
                        },
                        new
                        {
                            Id = 56,
                            CreatedDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 56. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 56",
                            Price = 318.99m,
                            Stock = 212
                        },
                        new
                        {
                            Id = 57,
                            CreatedDate = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 57. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 57",
                            Price = 324.49m,
                            Stock = 214
                        },
                        new
                        {
                            Id = 58,
                            CreatedDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 58. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 58",
                            Price = 329.99m,
                            Stock = 216
                        },
                        new
                        {
                            Id = 59,
                            CreatedDate = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 59. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 59",
                            Price = 335.49m,
                            Stock = 218
                        },
                        new
                        {
                            Id = 60,
                            CreatedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 60. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 60",
                            Price = 340.99m,
                            Stock = 220
                        },
                        new
                        {
                            Id = 61,
                            CreatedDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 61. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 61",
                            Price = 346.49m,
                            Stock = 222
                        },
                        new
                        {
                            Id = 62,
                            CreatedDate = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 62. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 62",
                            Price = 351.99m,
                            Stock = 224
                        },
                        new
                        {
                            Id = 63,
                            CreatedDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 63. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 63",
                            Price = 357.49m,
                            Stock = 226
                        },
                        new
                        {
                            Id = 64,
                            CreatedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 64. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 64",
                            Price = 362.99m,
                            Stock = 228
                        },
                        new
                        {
                            Id = 65,
                            CreatedDate = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 65. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 65",
                            Price = 368.49m,
                            Stock = 230
                        },
                        new
                        {
                            Id = 66,
                            CreatedDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 66. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 66",
                            Price = 373.99m,
                            Stock = 232
                        },
                        new
                        {
                            Id = 67,
                            CreatedDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 67. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 67",
                            Price = 379.49m,
                            Stock = 234
                        },
                        new
                        {
                            Id = 68,
                            CreatedDate = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 68. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 68",
                            Price = 384.99m,
                            Stock = 236
                        },
                        new
                        {
                            Id = 69,
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 69. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 69",
                            Price = 390.49m,
                            Stock = 238
                        },
                        new
                        {
                            Id = 70,
                            CreatedDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 70. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 70",
                            Price = 395.99m,
                            Stock = 240
                        },
                        new
                        {
                            Id = 71,
                            CreatedDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 71. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 71",
                            Price = 401.49m,
                            Stock = 242
                        },
                        new
                        {
                            Id = 72,
                            CreatedDate = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 72. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 72",
                            Price = 406.99m,
                            Stock = 244
                        },
                        new
                        {
                            Id = 73,
                            CreatedDate = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 73. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 73",
                            Price = 412.49m,
                            Stock = 246
                        },
                        new
                        {
                            Id = 74,
                            CreatedDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 74. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 74",
                            Price = 417.99m,
                            Stock = 248
                        },
                        new
                        {
                            Id = 75,
                            CreatedDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 75. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 75",
                            Price = 423.49m,
                            Stock = 250
                        },
                        new
                        {
                            Id = 76,
                            CreatedDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 76. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 76",
                            Price = 428.99m,
                            Stock = 252
                        },
                        new
                        {
                            Id = 77,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 77. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 77",
                            Price = 434.49m,
                            Stock = 254
                        },
                        new
                        {
                            Id = 78,
                            CreatedDate = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 78. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 78",
                            Price = 439.99m,
                            Stock = 256
                        },
                        new
                        {
                            Id = 79,
                            CreatedDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 79. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 79",
                            Price = 445.49m,
                            Stock = 258
                        },
                        new
                        {
                            Id = 80,
                            CreatedDate = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 80. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 80",
                            Price = 450.99m,
                            Stock = 260
                        },
                        new
                        {
                            Id = 81,
                            CreatedDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 81. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 81",
                            Price = 456.49m,
                            Stock = 262
                        },
                        new
                        {
                            Id = 82,
                            CreatedDate = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 82. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 82",
                            Price = 461.99m,
                            Stock = 264
                        },
                        new
                        {
                            Id = 83,
                            CreatedDate = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 83. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 83",
                            Price = 467.49m,
                            Stock = 266
                        },
                        new
                        {
                            Id = 84,
                            CreatedDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 84. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 84",
                            Price = 472.99m,
                            Stock = 268
                        },
                        new
                        {
                            Id = 85,
                            CreatedDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 85. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 85",
                            Price = 478.49m,
                            Stock = 270
                        },
                        new
                        {
                            Id = 86,
                            CreatedDate = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 86. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 86",
                            Price = 483.99m,
                            Stock = 272
                        },
                        new
                        {
                            Id = 87,
                            CreatedDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 87. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 87",
                            Price = 489.49m,
                            Stock = 274
                        },
                        new
                        {
                            Id = 88,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 88. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 88",
                            Price = 494.99m,
                            Stock = 276
                        },
                        new
                        {
                            Id = 89,
                            CreatedDate = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 89. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 89",
                            Price = 500.49m,
                            Stock = 278
                        },
                        new
                        {
                            Id = 90,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 90. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 90",
                            Price = 505.99m,
                            Stock = 280
                        },
                        new
                        {
                            Id = 91,
                            CreatedDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 91. It comes with great features and quality.",
                            ImageUrl = "/images/products/product2.jpg",
                            IsActive = true,
                            Name = "Clothing Product 91",
                            Price = 511.49m,
                            Stock = 282
                        },
                        new
                        {
                            Id = 92,
                            CreatedDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 92. It comes with great features and quality.",
                            ImageUrl = "/images/products/product3.jpg",
                            IsActive = true,
                            Name = "Books Product 92",
                            Price = 516.99m,
                            Stock = 284
                        },
                        new
                        {
                            Id = 93,
                            CreatedDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 93. It comes with great features and quality.",
                            ImageUrl = "/images/products/product4.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 93",
                            Price = 522.49m,
                            Stock = 286
                        },
                        new
                        {
                            Id = 94,
                            CreatedDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 94. It comes with great features and quality.",
                            ImageUrl = "/images/products/product5.jpg",
                            IsActive = true,
                            Name = "Sports Product 94",
                            Price = 527.99m,
                            Stock = 288
                        },
                        new
                        {
                            Id = 95,
                            CreatedDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 95. It comes with great features and quality.",
                            ImageUrl = "/images/products/product6.jpg",
                            IsActive = true,
                            Name = "Electronics Product 95",
                            Price = 533.49m,
                            Stock = 290
                        },
                        new
                        {
                            Id = 96,
                            CreatedDate = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample clothing product with ID 96. It comes with great features and quality.",
                            ImageUrl = "/images/products/product7.jpg",
                            IsActive = true,
                            Name = "Clothing Product 96",
                            Price = 538.99m,
                            Stock = 292
                        },
                        new
                        {
                            Id = 97,
                            CreatedDate = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample books product with ID 97. It comes with great features and quality.",
                            ImageUrl = "/images/products/product8.jpg",
                            IsActive = true,
                            Name = "Books Product 97",
                            Price = 544.49m,
                            Stock = 294
                        },
                        new
                        {
                            Id = 98,
                            CreatedDate = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample home & garden product with ID 98. It comes with great features and quality.",
                            ImageUrl = "/images/products/product9.jpg",
                            IsActive = true,
                            Name = "Home & Garden Product 98",
                            Price = 549.99m,
                            Stock = 296
                        },
                        new
                        {
                            Id = 99,
                            CreatedDate = new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample sports product with ID 99. It comes with great features and quality.",
                            ImageUrl = "/images/products/product10.jpg",
                            IsActive = true,
                            Name = "Sports Product 99",
                            Price = 555.49m,
                            Stock = 298
                        },
                        new
                        {
                            Id = 100,
                            CreatedDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample electronics product with ID 100. It comes with great features and quality.",
                            ImageUrl = "/images/products/product1.jpg",
                            IsActive = true,
                            Name = "Electronics Product 100",
                            Price = 560.99m,
                            Stock = 300
                        });
                });

            modelBuilder.Entity("ECommerce.Core.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerce.Core.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
